### ISSUE TITLE
Possible memory leaks ?

### ISSUE THREAD

**Issue by Pao-lino** [DevExpress-Examples/multiple-selection-using-checkbox-web-style-e1271#4]
For version 17.2.3, I took a look at the VB code.
It uses, AddHandler and RemoveHandler.
I know that a missing RemoveHandler can cause memory leaks.

GridCheckMarksSelection class does not implement IDisposable and in the Form1 class I see no call to Detach method.

Can it cause memory leaks ?

Thank you
Paolo

**Comment by LexEPoX** [comment]
Hello Paolo,

If you close the form with the grid, it will not cause any memory leaks. However, if you want to conditionally add/remove the selection column (and hiding it does not meet your requirements), you can make the **Detach** method public and call it manually.
